#!/bin/bash

#SBATCH -J pcv1
#SBATCH -o logs/%x-%j.log
#SBATCH -e logs/%x-%j.log
#SBATCH -p gh
#SBATCH -N 1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH -t 24:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jz963@cornell.edu
#SBATCH -a 0-1

module load gcc/13.2.0 cuda/12.4
module load python3/3.11.8

source $WORK/envs/transformers_440/bin/activate
source ~/.bashrc

# Environment variables
export TRITON_PTXAS_PATH=/opt/apps/cuda/12.4/bin/ptxas
export DATA_DIR=${CAD2}/results/Poaceae_CDS_PhyloP/512/

fnames=(
	"neutral_512_downsampled.tsv"
	"conserved_512_downsampled.tsv"
)

# get fname based on the SLURM_ARRAY_TASK_ID
fname=${fnames[$SLURM_ARRAY_TASK_ID]}

# the output is the replace .tsv with _pcv1_logits.tsv
OUTPUT_DIR=${DATA_DIR}${fname%.tsv}_pcv1_logits.tsv

python main.py -input ${DATA_DIR}${fname} \
     -outLogit ${OUTPUT_DIR} \
     -model 'kuleshov-group/PlantCaduceus_l32' \
     -device 'cuda:0' -batchSize 128 -tokenIdx 255


OUTPUT_DIR=../../../results/Poaceae_CDS_PhyloP/8k/conserved_8k_TIS_1_pcv1.tsv
python main.py \
    -outLogit ${OUTPUT_DIR} \
    -input ../../../results/Poaceae_CDS_PhyloP/8k/conserved_8k_TIS_1.tsv \
    -model 'kuleshov-group/PlantCaduceus_l32' \
    -device 'cuda:0'

OUTPUT_DIR=../../../results/Poaceae_CDS_PhyloP/8k/conserved_8k_TIS_2_pcv1.tsv
python main.py \
    -outLogit ${OUTPUT_DIR} \
    -input ../../../results/Poaceae_CDS_PhyloP/8k/conserved_8k_TIS_2.tsv \
    -model 'kuleshov-group/PlantCaduceus_l32' \
    -device 'cuda:0'

OUTPUT_DIR=../../../results/Poaceae_CDS_PhyloP/8k/conserved_8k_TIS_3_pcv1.tsv
python main.py \
    -outLogit ${OUTPUT_DIR} \
    -input ../../../results/Poaceae_CDS_PhyloP/8k/conserved_8k_TIS_3.tsv \
    -model 'kuleshov-group/PlantCaduceus_l32' \
    -device 'cuda:0'

## neutral
OUTPUT_DIR=../../../results/Poaceae_CDS_PhyloP/8k/neutral_8k_TIS_1_pcv1.tsv
python main.py \
    -outLogit ${OUTPUT_DIR} \
    -input ../../../results/Poaceae_CDS_PhyloP/8k/neutral_8k_TIS_1.tsv \
    -model 'kuleshov-group/PlantCaduceus_l32' \
    -device 'cuda:0'

OUTPUT_DIR=../../../results/Poaceae_CDS_PhyloP/8k/neutral_8k_TIS_2_pcv1.tsv
python main.py \
    -outLogit ${OUTPUT_DIR} \
    -input ../../../results/Poaceae_CDS_PhyloP/8k/neutral_8k_TIS_2.tsv \
    -model 'kuleshov-group/PlantCaduceus_l32' \
    -device 'cuda:0'

OUTPUT_DIR=../../../results/Poaceae_CDS_PhyloP/8k/neutral_8k_TIS_3_pcv1.tsv
python main.py \
    -outLogit ${OUTPUT_DIR} \
    -input ../../../results/Poaceae_CDS_PhyloP/8k/neutral_8k_TIS_3.tsv \
    -model 'kuleshov-group/PlantCaduceus_l32' \
    -device 'cuda:0'