#!/bin/bash

#SBATCH -J pcv2-large-1k
#SBATCH -o logs/%x-%j.log
#SBATCH -e logs/%x-%j.log
#SBATCH -p gh
#SBATCH -N 1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH -t 12:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jz963@cornell.edu
#SBATCH -a 0-1

module load gcc/13.2.0 cuda/12.5
module load python3/3.11.8

source $WORK/envs/transformers_440/bin/activate
source ~/.bashrc

# Environment variables
export TRITON_PTXAS_PATH=/home1/apps/nvidia/Linux_aarch64/24.7/cuda/12.5/bin/ptxas
export DATA_DIR=${CAD2}/results/Poaceae_CDS_PhyloP/1024/

fnames=(
	"neutral_1k_downsampled.tsv"
	"conserved_1k_downsampled.tsv"
)

# get fname based on the SLURM_ARRAY_TASK_ID
fname=${fnames[$SLURM_ARRAY_TASK_ID]}

# the output is the replace .tsv with _pcv1_logits.tsv
OUTPUT_DIR=${DATA_DIR}${fname%.tsv}_pcv2-l48-d1536_logits_batchSize_32.tsv

python main.py -input ${DATA_DIR}${fname} \
     -outLogit ${OUTPUT_DIR} \
     -model 'kuleshov-group/compo-cad2-l48-d1536-dna-chtk-c8k-1t-v1-b2-lr4e4-NzqiLr' \
     -device 'cuda:0' -batchSize 32 -tokenIdx 511
