#!/bin/bash

#SBATCH -J  predict_max_exp_agront # Job name
#SBATCH -o logs/%x.log      # Name of stdout output file
#SBATCH -e logs/%x.log      # Name of stderr error file
#SBATCH -p gh               # Queue (partition) name
#SBATCH -N 4                # Total # of nodes
#SBATCH -n 4                # Total # of mpi tasks
#SBATCH -t 03:00:00         # Run time (hh:mm:ss)
#SBATCH --mail-type=BEGAN,END,FAIL     # Send email at begin and end of job
#SBATCH --mail-user=jz963@cornell.edu

module load gcc/13.2.0 cuda/12.4
module load python3/3.11.8
export TRITON_PTXAS_PATH=/opt/apps/cuda/12.4/bin/ptxas

export DATA_DIR=${cad2}/results/PlantCAD2_tasks/exp-max
export CHECKPOINT_DIR="${DATA_DIR}/agront-checkpoints-lr-1e-4/checkpoint-7975"
export MODEL_NAME="InstaDeepAI/agro-nucleotide-transformer-1b"

source $WORK/envs/PlantCAD/bin/activate
source ~/.bashrc

# Predict on valid
srun -l python main.py predict_distributed --checkpoint_dir $CHECKPOINT_DIR --data_dir ${DATA_DIR}/valid.agront.parquet \
    --model_name ${MODEL_NAME} \
    --task_type 'regression' \
    --batch_size 32 \
    --output_file ${DATA_DIR}/agront-checkpoints-lr-1e-4/valid_predictions.tsv

# Predict on test
srun -l python main.py predict_distributed --checkpoint_dir $CHECKPOINT_DIR --data_dir ${DATA_DIR}/test.agront.parquet \
    --model_name ${MODEL_NAME} \
    --task_type 'regression' \
    --batch_size 32 \
    --output_file ${DATA_DIR}/agront-checkpoints-lr-1e-4/test_predictions.tsv
