#!/bin/bash

#SBATCH -J sup_pcv2-l24-d0768-abs # Job name
#SBATCH -o logs/%x.log      # Name of stdout output file
#SBATCH -e logs/%x.log      # Name of stderr error file
#SBATCH -p gh               # Queue (partition) name
#SBATCH -N 1                # Total # of nodes (must be 1 for serial)
#SBATCH -n 1                # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 24:00:00         # Run time (hh:mm:ss)
#SBATCH --mail-type=BEGAN,END,FAIL     # Send email at begin and end of job
#SBATCH --mail-user=jz963@cornell.edu

module load gcc/13.2.0 cuda/12.4
module load python3/3.11.8
export TRITON_PTXAS_PATH=/opt/apps/cuda/12.4/bin/ptxas

export DATA_DIR=/work/10373/jzhai/vista/utils/plantcad2/results/PlantCAD2_tasks/exp-leaf-abs
export OUTPUT_DIR="${DATA_DIR}/sup_pcv2-l24-d0768-checkpoints-lr-1e-4"
export CHECKPOINTS="${OUTPUT_DIR}/checkpoint-7975"

source $WORK/envs/PlantCAD/bin/activate
source ~/.bashrc

python main.py predict \
    --data_dir=$DATA_DIR/test.parquet \
    --checkpoint_dir=$CHECKPOINTS \
    --output_file=$OUTPUT_DIR/predictions.csv \
    --task_type 'regression'
