#!/bin/bash

#SBATCH -J  pcv2-large # Job name
#SBATCH -o logs/%x_%A_%a.log  # Name of stdout output file (includes array task ID)
#SBATCH -e logs/%x_%A_%a.log  # Name of stderr error file (includes array task ID)
#SBATCH -p gh                 # Queue (partition) name
#SBATCH -N 1                  # Total # of nodes (must be 1 for serial)
#SBATCH -n 1                  # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 24:00:00           # Run time (hh:mm:ss)
#SBATCH --mail-type=BEGIN,END,FAIL  # Send email at begin and end of job
#SBATCH --mail-user=jz963@cornell.edu
#SBATCH -a 0-8                # Array range (0-2 for 3 species)

module load gcc/13.2.0 cuda/12.4
module load python3/3.11.8
export TRITON_PTXAS_PATH=/opt/apps/cuda/12.4/bin/ptxas

export DATA_DIR=/scratch/10373/jzhai/utils/plantcad2/results/translation_efficiency/training_data/2_bin/
export OUTPUT_DIR="${DATA_DIR}/models/pcv2-l48-d1536"
export CKPT_DIR="${OUTPUT_DIR}/checkpoint-171"

source $WORK/envs/PlantCAD/bin/activate
source ~/.bashrc

# Define the species array
# Get the species for the current array task
species_array=(valid_ism_000 valid_ism_001 valid_ism_002 valid_ism_003 valid_ism_004 valid_ism_005 valid_ism_006 valid_ism_007 valid_ism_008)


# Get the species for the current array task
species=${species_array[$SLURM_ARRAY_TASK_ID]}

# Run the command for the current species
python ../main.py predict \
    --checkpoint_dir ${CKPT_DIR} \
    --data_dir ${DATA_DIR}/${species}.parquet \
    --output_file ${OUTPUT_DIR}/${species}_scores.tsv \
    --model_name "kuleshov-group/compo-cad2-l48-d1536-dna-chtk-c8k-1t-v1-b2-lr4e4-NzqiLr" \
    --batch_size 64
